In [2]:
import numpy as np
from numpy.linalg import norm

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    

Необходимо, чтобы число столбцов матрицы А было равно числу строк матрицы В.

$Вывод:$

a) AB и BA не определены;

б) AB - размерность 2x3, BA не определена;

в) AB размерность 8x8, BA размерность 3x3;

г) AB и BA размерность 4x4;

а) A — матрица 4×2 , B — матрица 4×2:

In [3]:
A = np.ones((4,2))
B = np.ones((4,2))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Матрица B
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

б) A — матрица 2×5 , B — матрица 5×3:

In [4]:
A = np.ones((2,5))
B = np.ones((5,3))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Матрица B
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Матрица AB
[[5. 5. 5.]
 [5. 5. 5.]]


ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

в) A — матрица 8×3 , B — матрица 3×8:

In [5]:
A = np.ones((8,3))
B = np.ones((3,8))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Матрица B
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
Матрица AB
[[3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]]
Матрица BA
[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


г) A — квадратная матрица 4×4 , B — квадратная матрица 4×4:

In [6]:
A = np.ones((4,4))
B = np.ones((4,4))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Матрица B
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Матрица AB
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
Матрица BA
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B =$

$\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$A * B =$

$\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A=:$

$\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$

$2B=:$

$\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$

$4C=:$

$\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$

$3A-2B+4C=$

$\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [10]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{B}')
print(f'Матрица 3A-2B+4C\n{3*A+(-2)*B+4*C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица C
[[ 0  5]
 [ 2 -1]]
Матрица 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [13]:
A = np.array([[4,1],[5,-2],[2,3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'матрица A*AT:\n{np.dot(A,A.T)}')
print(f'матрица AT*A:\n{np.dot(A.T,A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
матрица A*AT:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
матрица AT*A:
[[45  0]
 [ 0 14]]


__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a)$det(A)= sin^{2}(x)+ cos^{2}(x)$

б)$det(A)= 180$

в)$det(A)= 0$

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

$а)det(A^{2}) = det(A)*det(A)= 16;$

$б)det(A^{Т}) = det(A)= 4;$

$в)det(2A) = 2*det(A)= 8;$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Найдем определитель:
$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}$$

$𝑑𝑒𝑡(𝐴)=0$

Матрица является вырожденной.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Приведем матрицу к треугольному виду. Будем работать только со строками, так как умножение строки матрицы на число, отличное от нуля, и прибавление к другой строке для системы означает умножение уравнения на это же число и сложение с другим уравнением, что не меняет решения системы. 

Умножим 1-ую строку на (-1). Добавим 2-ую строку к 1-ой: 

$\begin{pmatrix}
0 & -1 & -2\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Умножим 2-ую строку на (-2). Добавим 3-ую строку к 2-ой: 

$\begin{pmatrix}
0 & -1 & -2\\ 
0 & 1 & 2\\ 
2 & 3 & 4
\end{pmatrix};$

В матрице B 1-ая и 2-ая строки пропорциональны, следовательно, одну из них, например 1-ю, можно вычеркнуть. Это равносильно вычеркиванию 1-го уравнения системы, так как оно является следствием 2-го.

Полученная матрица имеет размерность 2x3.

$\begin{pmatrix}
0 & 1 & 2\\ 
2 & 3 & 4 
\end{pmatrix};$

Выделенный минор имеет наивысший порядок (из возможных миноров) и отличен от нуля (он равен произведению элементов, стоящих на обратной диагонали), следовательно rang(A) = 2

б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Приведем матрицу к треугольному виду. Будем работать только со строками, так как умножение строки матрицы на число, отличное от нуля, и прибавление к другой строке для системы означает умножение уравнения на это же число и сложение с другим уравнением, что не меняет решения системы. 

Умножим 1-ую строку на (-1). Добавим 2-ую строку к 1-ой: 

$\begin{pmatrix}
0 & 0 & 0 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Выделенный минор имеет наивысший порядок (из возможных миноров) и отличен от нуля (он равен произведению элементов, стоящих на обратной диагонали), следовательно rang(A) = 4
